### ISSUE TITLE
Cannot run angular app

### ISSUE THREAD

**Issue by lamemmv** [robisim74/Angular2SPAWebAPI#19]
When i try to tun npm start, I got this error:

```
Loading...
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./app/styles.scss
Module build failed: Error: Missing binding F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./app/styles.scss 4:14-118 18:2-22:4 19:20-124
 @ ./app/main.ts
 @ multi webpack-hot-middleware/client?path=%2F__webpack_hmr ./app/main.ts
ERROR in ./app/home/home.component.scss
Module build failed: Error: Missing binding F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./app/home/home.component.ts 14:21-53
 @ ./app/app.module.ts
 @ ./app/main.ts
 @ multi webpack-hot-middleware/client?path=%2F__webpack_hmr ./app/main.ts
ERROR in ./app/resources/resources.component.scss
Module build failed: Error: Missing binding F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./app/resources/resources.component.ts 28:21-58
 @ ./app/resources/resources.module.ts
 @ ./app/app-routing.module.ts
 @ ./app/app.module.ts
 @ ./app/main.ts
 @ multi webpack-hot-middleware/client?path=%2F__webpack_hmr ./app/main.ts
ERROR in ./app/dashboard/dashboard.component.scss
Module build failed: Error: Missing binding F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\lamemmv\study\self-study\asp.net\AngularSPAWebAPI-master\src\AngularSPAWebAPI\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./app/dashboard/dashboard.component.ts 38:21-58
 @ ./app/dashboard/dashboard.module.ts
 @ ./app/app-routing.module.ts
 @ ./app/app.module.ts
 @ ./app/main.ts
 @ multi webpack-hot-middleware/client?path=%2F__webpack_hmr ./app/main.ts
```

What're my missing?
Thanks

**Comment by robisim74** [comment]
This sometimes happens with `node-sass` if
>your environment has changed since running `npm install`

Try this:
- Make sure your configuration for external tools in VS is correct as explained in the README (if you are using VS)
- Update your _nodejs_ and _npm_ versions
- Close VS, remove manually _node_modules_ and run `npm install` from the command line

Then it should work.
