### ISSUE TITLE
error on 'npm start'

### ISSUE THREAD

**Issue by nadavten** [robisim74/Angular2SPAWebAPI#6]
ERROR in ./~/css-loader!./~/sass-loader!./app/styles/blue-amber.scss
Module build failed: Error: Missing binding C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\node-sass\vendor\win32-x64-51\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 7.x

Found bindings for the following environments:
  - Windows 32-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
    at iteratePitchingLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:160:10)
    at C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:168:18
    at loadLoader (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
    at runLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:357:2)
    at NormalModule.doBuild (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModule.js:131:2)
    at NormalModule.build (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModule.js:181:15)
    at Compilation.buildModule (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\Compilation.js:129:9)
    at factoryCallback (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\Compilation.js:308:10)
    at C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModuleFactory.js:243:4
    at C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModuleFactory.js:94:13
 @ ./app/styles/blue-amber.scss 4:14-127
 @ ./app/main.ts

ERROR in ./~/css-loader!./~/sass-loader!./app/styles/app.scss
Module build failed: Error: Missing binding C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\node-sass\vendor\win32-x64-51\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 7.x

Found bindings for the following environments:
  - Windows 32-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
    at iteratePitchingLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:160:10)
    at C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:168:18
    at loadLoader (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
    at runLoaders (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\loader-runner\lib\LoaderRunner.js:357:2)
    at NormalModule.doBuild (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModule.js:131:2)
    at NormalModule.build (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModule.js:181:15)
    at Compilation.buildModule (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\Compilation.js:129:9)
    at factoryCallback (C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\Compilation.js:308:10)
    at C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModuleFactory.js:243:4
    at C:\Users\nadav\Desktop\Angular2SPAWebAPI-master\src\Angular2SPAWebAPI\node_modules\webpack\lib\NormalModuleFactory.js:94:13
 @ ./app/styles/app.scss 4:14-120
 @ ./app/main.ts

**Comment by robisim74** [comment]
Try to update your npm version to the latest, then remove node_modules and restore the packages. If it still doesn't work, try to install node-sass globally.

**Comment by robisim74** [comment]
I discovered another reason why this issue can occur: make sure your configuration for external tools is correct: https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/
